import { Product, Category } from './types';

// Categories that match both website and mobile app
export const categories: Category[] = [
  {
    id: '1',
    name: '蔬菜/淨菜加工類',
    description: '新鮮蔬菜及淨菜加工產品',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    subcategories: ['葉菜類', '根莖類', '淨菜加工']
  },
  {
    id: '2',
    name: '糧油乾貨類',
    description: '各種糧油和乾貨產品',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    subcategories: ['米麵', '食用油', '調味料', '乾貨']
  },
  {
    id: '3',
    name: '進口凍肉類',
    description: '優質進口冷凍肉類',
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1fdc82f?w=400',
    subcategories: ['牛肉', '豬肉', '雞肉', '羊肉']
  },
  {
    id: '4',
    name: '進口海產類',
    description: '新鮮進口海產',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    subcategories: ['魚類', '蝦類', '貝類', '蟹類']
  },
  {
    id: '5',
    name: '半加工及預製食品類',
    description: '半加工和預製食品',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    subcategories: ['半成品', '預製菜', '調理包']
  },
  {
    id: '6',
    name: '烘焙甜品類',
    description: '烘焙產品和甜品',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    subcategories: ['麵包', '蛋糕', '甜點', '餅乾']
  },
  {
    id: '7',
    name: '飲品材料類',
    description: '各種飲品和材料',
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400',
    subcategories: ['茶葉', '咖啡', '果汁', '調味品']
  },
  {
    id: '8',
    name: '清潔用品類',
    description: '清潔和衛生用品',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c6a0c3f2fcc0?w=400',
    subcategories: ['清潔劑', '消毒用品', '紙製品']
  },
  {
    id: '9',
    name: '酒精類',
    description: '各種酒精飲品',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400',
    subcategories: ['啤酒', '紅酒', '白酒', '烈酒']
  }
];

// Products that match both website and mobile app
export const products: Product[] = [
  // 蔬菜/淨菜加工類
  {
    id: '1',
    name: '有機菠菜',
    description: '新鮮有機菠菜，富含鐵質和維生素',
    category: '蔬菜/淨菜加工類',
    subcategory: '葉菜類',
    price: 45,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
    isAvailable: true,
    supplier: '有機農場',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: '淨菜綜合包',
    description: '預處理好的綜合蔬菜包，方便使用',
    category: '蔬菜/淨菜加工類',
    subcategory: '淨菜加工',
    price: 80,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    isAvailable: true,
    supplier: '淨菜工廠',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: '新鮮胡蘿蔔',
    description: '當季新鮮胡蘿蔔，甜脆可口',
    category: '蔬菜/淨菜加工類',
    subcategory: '根莖類',
    price: 35,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 150,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
    isAvailable: true,
    supplier: '有機農場',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 糧油乾貨類
  {
    id: '4',
    name: '優質白米',
    description: '優質白米，香Q可口',
    category: '糧油乾貨類',
    subcategory: '米麵',
    price: 95,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 200,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    isAvailable: true,
    supplier: '糧食專賣',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: '特級初榨橄欖油',
    description: '進口特級初榨橄欖油',
    category: '糧油乾貨類',
    subcategory: '食用油',
    price: 120,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 80,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    isAvailable: true,
    supplier: '糧食專賣',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: '純釀醬油',
    description: '傳統純釀醬油，香醇濃郁',
    category: '糧油乾貨類',
    subcategory: '調味料',
    price: 75,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 150,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    isAvailable: true,
    supplier: '糧食專賣',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 進口凍肉類
  {
    id: '7',
    name: '澳洲進口牛肉',
    description: '澳洲進口優質牛肉，肉質鮮嫩',
    category: '進口凍肉類',
    subcategory: '牛肉',
    price: 450,
    unit: '公斤',
    minOrderQuantity: 1,
    stockQuantity: 30,
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1fdc82f?w=400',
    isAvailable: true,
    supplier: '進口肉品',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: '美國進口豬肉',
    description: '美國進口冷凍豬肉，品質優良',
    category: '進口凍肉類',
    subcategory: '豬肉',
    price: 280,
    unit: '公斤',
    minOrderQuantity: 1,
    stockQuantity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1fdc82f?w=400',
    isAvailable: true,
    supplier: '進口肉品',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: '巴西進口雞肉',
    description: '巴西進口冷凍雞肉，無激素',
    category: '進口凍肉類',
    subcategory: '雞肉',
    price: 180,
    unit: '公斤',
    minOrderQuantity: 1,
    stockQuantity: 80,
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400',
    isAvailable: true,
    supplier: '進口肉品',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 進口海產類
  {
    id: '10',
    name: '挪威進口鮭魚',
    description: '挪威進口新鮮鮭魚，富含Omega-3',
    category: '進口海產類',
    subcategory: '魚類',
    price: 680,
    unit: '公斤',
    minOrderQuantity: 1,
    stockQuantity: 25,
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    isAvailable: true,
    supplier: '海鮮進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: '阿根廷進口紅蝦',
    description: '阿根廷進口紅蝦，肉質鮮甜',
    category: '進口海產類',
    subcategory: '蝦類',
    price: 520,
    unit: '公斤',
    minOrderQuantity: 1,
    stockQuantity: 40,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    isAvailable: true,
    supplier: '海鮮進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '12',
    name: '法國進口生蠔',
    description: '法國進口新鮮生蠔，品質優良',
    category: '進口海產類',
    subcategory: '貝類',
    price: 1200,
    unit: '打',
    minOrderQuantity: 1,
    stockQuantity: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    isAvailable: true,
    supplier: '海鮮進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 半加工及預製食品類
  {
    id: '13',
    name: '預製紅燒肉',
    description: '半成品紅燒肉，加熱即可食用',
    category: '半加工及預製食品類',
    subcategory: '預製菜',
    price: 180,
    unit: '份',
    minOrderQuantity: 1,
    stockQuantity: 60,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    isAvailable: true,
    supplier: '預製食品廠',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '14',
    name: '冷凍水餃',
    description: '手工冷凍水餃，多種口味',
    category: '半加工及預製食品類',
    subcategory: '半成品',
    price: 120,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    isAvailable: true,
    supplier: '預製食品廠',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '15',
    name: '調理包咖哩',
    description: '即食調理包咖哩，多種口味',
    category: '半加工及預製食品類',
    subcategory: '調理包',
    price: 85,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 80,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    isAvailable: true,
    supplier: '預製食品廠',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 烘焙甜品類
  {
    id: '16',
    name: '手工歐式麵包',
    description: '手工製作歐式麵包，外酥內軟',
    category: '烘焙甜品類',
    subcategory: '麵包',
    price: 65,
    unit: '條',
    minOrderQuantity: 1,
    stockQuantity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    isAvailable: true,
    supplier: '烘焙坊',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '17',
    name: '起司蛋糕',
    description: '經典起司蛋糕，口感綿密',
    category: '烘焙甜品類',
    subcategory: '蛋糕',
    price: 280,
    unit: '個',
    minOrderQuantity: 1,
    stockQuantity: 20,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
    isAvailable: true,
    supplier: '烘焙坊',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '18',
    name: '手工餅乾',
    description: '手工製作餅乾，多種口味',
    category: '烘焙甜品類',
    subcategory: '餅乾',
    price: 45,
    unit: '包',
    minOrderQuantity: 1,
    stockQuantity: 120,
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400',
    isAvailable: true,
    supplier: '烘焙坊',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 飲品材料類
  {
    id: '19',
    name: '阿里山高山茶',
    description: '台灣阿里山高山茶，香氣清雅',
    category: '飲品材料類',
    subcategory: '茶葉',
    price: 380,
    unit: '盒',
    minOrderQuantity: 1,
    stockQuantity: 40,
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400',
    isAvailable: true,
    supplier: '茶葉專賣',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '20',
    name: '藍山咖啡豆',
    description: '牙買加藍山咖啡豆，香濃醇厚',
    category: '飲品材料類',
    subcategory: '咖啡',
    price: 450,
    unit: '磅',
    minOrderQuantity: 1,
    stockQuantity: 25,
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400',
    isAvailable: true,
    supplier: '咖啡專賣',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '21',
    name: '新鮮檸檬汁',
    description: '100%純天然檸檬汁',
    category: '飲品材料類',
    subcategory: '果汁',
    price: 120,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 60,
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400',
    isAvailable: true,
    supplier: '果汁工廠',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 清潔用品類
  {
    id: '22',
    name: '餐廳專用清潔劑',
    description: '專業餐廳清潔劑，強效去污',
    category: '清潔用品類',
    subcategory: '清潔劑',
    price: 180,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 80,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c6a0c3f2fcc0?w=400',
    isAvailable: true,
    supplier: '清潔用品商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '23',
    name: '食品級消毒水',
    description: '食品級消毒水，安全有效',
    category: '清潔用品類',
    subcategory: '消毒用品',
    price: 220,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c6a0c3f2fcc0?w=400',
    isAvailable: true,
    supplier: '清潔用品商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '24',
    name: '廚房用紙',
    description: '高品質廚房用紙，吸水強',
    category: '清潔用品類',
    subcategory: '紙製品',
    price: 95,
    unit: '箱',
    minOrderQuantity: 1,
    stockQuantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c6a0c3f2fcc0?w=400',
    isAvailable: true,
    supplier: '清潔用品商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 酒精類
  {
    id: '25',
    name: '德國進口啤酒',
    description: '德國進口精釀啤酒，口感醇厚',
    category: '酒精類',
    subcategory: '啤酒',
    price: 85,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 200,
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400',
    isAvailable: true,
    supplier: '酒類進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '26',
    name: '法國波爾多紅酒',
    description: '法國波爾多地區紅酒，香氣濃郁',
    category: '酒精類',
    subcategory: '紅酒',
    price: 1200,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 30,
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400',
    isAvailable: true,
    supplier: '酒類進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '27',
    name: '日本清酒',
    description: '日本進口清酒，口感清雅',
    category: '酒精類',
    subcategory: '白酒',
    price: 680,
    unit: '瓶',
    minOrderQuantity: 1,
    stockQuantity: 25,
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400',
    isAvailable: true,
    supplier: '酒類進口商',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

// Helper function to get products by category
export const getProductsByCategory = (categoryName: string): Product[] => {
  return products.filter(product => product.category === categoryName);
};

// Helper function to get products by category ID
export const getProductsByCategoryId = (categoryId: string): Product[] => {
  const category = categories.find(cat => cat.id === categoryId);
  if (!category) return [];
  return products.filter(product => product.category === category.name);
};

// Helper function to get all categories
export const getAllCategories = (): Category[] => {
  return categories;
}; 